### ISSUE TITLE
TypeError: appInsights.start is not a function

### ISSUE THREAD

**Issue by rodneyjoyce** [johnhidey/angular-appinsights#12]
Hi,

I have followed the instructions (3 times ;) and keep getting this error onload:  "TypeError: appInsights.start is not a function"

It's happening on this line of code:

```
            if (appInsights && appId) {
                appInsights.start(appId);
            }
```

is this library still functional?

**Comment by dennismi** [comment]
Hey

I'm still using without any errors... 

Please provide more information...

**Comment by AVeryBritishDeveloper** [comment]
Hi, 

This has happened for me as well. I suspect MS have changed the client JS  lib that is shipped for AI (it is still in preview after all). I couldn't find anything from MS about it, but playing with the code I got it working by allowing the instrumentation key to be set as per the MS docs - i.e. _not_ performing the following:

```javascript
({//<-- remove this
  instrumentationKey:"your key here"//<-- remove this
})//<-- remove this
```
I also commented out the line in angular-appinsight.js as have init AI already

```javascript
appInsights({instrumentationKey:appId});
```


Also a number of the methods have changed - bringing it inline with other languages.
```javascript
appInsights.logPageView  -> appInsights.trackPageView
appInsights.logEvent  -> appInsights.trackEvent
```
etc.

Hope this helps

**Comment by dennismi** [comment]
that is just plain weird... i haven't changed a thing in my code and it still works... 

But the information helps..

Unfortunately, i am in the middle of moving, so internet connectivity and time is in short supply :)

But feel free to either comment with a potential fix, or clone and do a pull request (although i'm not at liberty to accept pull request) but i've got a clone, which you can clone and make a pull request from :)

**Comment by rahulbisht225** [comment]
I am also facing the same issue.I have tried the solution with pre-release version and it was working but once i tried with angular-appinsights.js version 1.0.0. it is giving me " appInsights.start is not a function"

**Comment by rahulbisht225** [comment]
Can you please update the file version of angular-appinsight.js in nuggetPackage Manager also.As it is referring to old version(i.e. 2014/07/08) and in github this file is updated on Dec 23rd, 2014.

Please update it in nugget package .

**Comment by gligoran** [comment]
Not sure, if this was the case when the issue was opened, but the `<script>` snippet that Azure provides has changed. I used that and removed the 4 lines as indicated in the README.md and it works.
