### ISSUE TITLE
Play nice with ui.router

### ISSUE THREAD

**Issue by fthiemonge** [johnhidey/angular-appinsights#14]
I have the same issue cited here due to my use of ui.router: http://blog.devdivision.co.za/ and http://stackoverflow.com/questions/28485388/angularjs-module-bootstrap-issues-angular-appinsights but cringe at the thought of editing the run method in code that's not my own. Yes, it's a simple edit, but still. Perhaps there's a way to work out of the box for both ngRoute and ui.router?

**Comment by johnhidey** [comment]
Issue has been resolved in v0.0.4
