### ISSUE TITLE
TypeError: insights.startTrackPage is not a function

### ISSUE THREAD

**Issue by seanfisher** [johnhidey/angular-appinsights#19]
This error is occurring for me on https://github.com/johnhidey/angular-appinsights/blob/master/lib/angular-appinsights.js#L76 on first time page load:

> TypeError: insights.startTrackPage is not a function

Seems to be related to [this StackOverflow post](http://stackoverflow.com/questions/30058310/using-starttrackpage-in-application-insights), suggesting:

> The reason is that startTrackPage() method is only defined in the JS that is downloaded from CDN, so until it is downloaded it is not defined.

I'm using the Microsoft-provided snippet to load the app insights SDK from their CDN.

**Comment by johnhidey** [comment]
This should be resolved by pull request #21 which adds in a check to ensure that startTrackPage is there before calling it.  If you continue to see this error please let me know.
