### ISSUE TITLE
Error: [$injector:modulerr] Failed to instantiate module shared due to: TypeError: appInsights.start is not a function     at Object.start (http://localhost/Scripts/angular-appinsights.js:20:33)

### ISSUE THREAD

**Issue by preetksingh80** [johnhidey/angular-appinsights#23]
Failing to start the module,

TypeError: appInsights.start is not a function
    at Object.start (http://localhost/Scripts/angular-appinsights.js:20:33)

shared.config(['$stateProvider', '$httpProvider', 'insightsProvider', function ($stateProvider, $httpProvider, insightsProvider) {
    $stateProvider
        .state('preview', {
        url: '/preview/:id',
        controller: "previewController as preview",
            templateUrl: 'app/shared/preview/preview.html'
        });
    insightsProvider.start('key');

**Comment by vskh** [comment]
Does not seem to work for me either.
Starting from the fact that I can't instantiate appInsights using default javascript snippet without providing instrumentation key. The API must have been changed.

**Comment by vskh** [comment]
Figured it out - I was confused by the version available in NuGet repo which seems to be old. After taking the module source directly from source here and modifying AI initialization code to not invoke the config function (removed ({})), everything started working.

**Comment by johnhidey** [comment]
@vskh @preetksingh80 The package on nuget.org is no longer being updated/maintained.  The package is only maintained on [npmjs.org](https://www.npmjs.com/package/angular-appinsights) and also [bower.io](https://bower.io).
