### ISSUE TITLE
Implement rest of Azure Application Insights

### ISSUE THREAD

**Issue by dennismi** [johnhidey/angular-appinsights#5]
Implement the 3 following function available when using Azure Application insigts:

1. Exception
2. Metric
3. Trace

(i am willing to provide the implementation : )

**Comment by johnhidey** [comment]
@dennismi Were you planning on taking a shot at the implemenation of Exception, Metric & Trace?  If not, let me know and I'll start looking into it as time allows.

**Comment by dennismi** [comment]
yes was planning to take a shot, but was swamped with real life :)

perhaps break the backlog item into 3, one for each method.. then it is
easier to implement then separately :=)

mvh
Dennis Micheelsen
Glambækvej 7
DK-5550 Langeskov
28 14 95 04

**Comment by johnhidey** [comment]
I'll break your request into 3 backlog items later today.

**Comment by johnhidey** [comment]
Created 3 separate issues for this items.  Issue #9 #10 and #11 will be used to track development of these items independently.
